### ISSUE TITLE
Validation is not appearing fine

### ISSUE THREAD

**Issue by srikiran-mulasa** [Daemonite/material#101]
After entering input should become red if there is an error.

but im using AngularJS for dom manipulation here ng-reqired is behaving differently so im using required for input, select box, textarea which is appearing in red without entering value and not appearing green if the entered value is correct.
![error](https://cloud.githubusercontent.com/assets/3609212/16712166/29379c2e-469c-11e6-801a-ac9ae9195121.PNG)       

**is my code**

<div class="col-lg-2 col-md-2 col-sm-2 col-xx-4">
                                    <div class="form-group form-group-label" style="margin-bottom: 0px;margin-top: 24px;">
                                        <label class="floating-label" for="country_code">Country Code</label>
                                        <input id="country_code" class="form-control" type="number" name="countryCode"
                                          ng-model = "user.countryCode" ng-pattern="/^[0-9]/" ng-required = "true" >
                                        <span style="color:red" ng-show="Details.countryCode.$dirty && Details.countryCode.$invalid">
                                            <span ng-show="Details.countryCode.$error.required">You can't leave this empty</span>
                                            <span ng-show="Details.countryCode.$error.minlength">country Code should be 5</span> 
                                            <span ng-show="Details.countryCode.$error.pattern">Numbers and special characters are not allowed</span> 
                                        </span>
                                    </div>

```
                            </div>
                            <!--Country code ends here-->
                            <!--Phone  starts here-->
                            <div class="col-lg-4 col-md-4 col-sm-4 col-xx-8">
                                <div class="form-group form-group-label" style="margin-bottom: 0px;margin-top: 24px;">
                                    <label class="floating-label" for="phone_number">Phone Number</label>
                                    <input id="phone_number" class="form-control" type="number" ng-model = "user.phone" name="phone" ng-required="true">
                                    <span style="color:red" ng-show="Details.phone.$dirty && Details.phone.$invalid">
                                        <span  class="error" ng-show="Details.phone.$error.required">Required!</span>
                                        <span ng-show="Details.phone.$error.minlength">Phone Number should be 10 digits</span>
                                    </span>
                                </div>
                            </div>
```

**Comment by sesemaya** [comment]
Fixed by 2f4329469a05a251956c29c47920f145a577b1bb
