### ISSUE TITLE
no javascript dropdown() function?

### ISSUE THREAD

**Issue by cloudstoneme** [Daemonite/material#117]
I just realized that there is no dropdown() function in javascript. Is this a bug or on some purpose?

**Comment by sesemaya** [comment]
@cloudstoneme `dropdown()` is part of `bootstrap.js`.

`material.js` does not replace `bootstrap.js`, it is used to add additional Material feel and look to some components/elements.

Details of dropdown can be found here: http://daemonite.github.io/material/gh-pages/components/dropdowns/index.html#usage
