### ISSUE TITLE
Implement required field validation

### ISSUE THREAD

**Issue by plrenaudin** [Daemonite/material#12]
Hello,
First of all, it's a great material design implementation!

Maybe I missed something but I don't find a way to make a form field mandatory the same way as in : https://www.polymer-project.org/0.5/components/paper-input/demo.html

Regards,

PL

**Comment by sesemaya** [comment]
hi @plrenaudin is the following code what you are looking for?

```html
<div class="form-group form-group-label form-group-red">
	<div class="row">
		<div class="col-lg-6 col-sm-8">
			<label class="floating-label" for="input-required">Required</label>
			<input class="form-control" id="input-required" type="text">
			<span class="form-help form-help-msg text-red">Input is required<i class="form-help-icon icon icon-warning"></i></span>
		</div>
	</div>
</div>
```

**Comment by plrenaudin** [comment]
Hi @sesemaya,
Thanks for replying.
The behavior of a required field is not the same on the polymer element: once you fill it in, the warning disappear.
The best way would be to handle this the same as the required attribute on a html input : display the warning on the form submit.

**Comment by shib71** [comment]
Couldn't you implement this yourself with JavaScript? Incorporating
specific behaviours is a little beyond the focus of this project, which is
design and page structure.

**Comment by plrenaudin** [comment]
Ok, I found a small workaround anyway which works for me without JS.
I added those lines at the end of base.css
```
.form-control:invalid, .form-control:invalid + .floating-label{
  color:red;
  border-bottom-color:red;
}
```
