### ISSUE TITLE
Floating action button / Fab button

### ISSUE THREAD

**Issue by derekphilipau** [Daemonite/material#121]
Currently using material in a new project.  Awesome work, including the exhaustive documentation.

Any plans to implement a circular "Floating action button"?

I've tried various CSS solutions found online with poor results.  Right now I'm using this, but it's not good:
```
.btn-round {
  @extend .rounded-circle;
  padding: .65rem;
  font-size: 1.2rem;
  min-width: 0;
  width: 2.5rem;
  height: 2.5rem;
}

.btn-round.btn-lg {
  @extend .rounded-circle;
  padding: .95rem;
  font-size: 1.6rem;
  min-width: 0;
  width: 3.5rem;
  height: 3.5rem;
}
```

**Comment by sesemaya** [comment]
Floating action button is already supported: `.btn .btn-float`.

It also works with helper classes such as `.btn-danger` or `.btn-primary` for different colour options, and `.btn-sm` for a smaller floating action button.

More documentation about Material components will be gradually added to this project. Some have already been done in the `backfilling-bootstrap-v4.0.0-beta` branch. Feel free to check it out.
