### ISSUE TITLE
(Fix) Problem with Cards and Modal

### ISSUE THREAD

**Issue by loonix** [Daemonite/material#122]
When you create a modal inside card class this will be in background instead of a absolute position.

Quick fix should be:

.btn-float, .card {
    position: inherit;
}

**Comment by sesemaya** [comment]
Without a bit more information about the issue, little can be actioned here.

**Comment by loonix** [comment]
Example of it using my CSS fix:
![image](https://cloud.githubusercontent.com/assets/3384277/24114921/adeec09a-0d99-11e7-9e95-18c41248cbdc.png)

Example of using your code:
![image](https://cloud.githubusercontent.com/assets/3384277/24115047/0bb93494-0d9a-11e7-8f8b-0b8e58197344.png)

doesn't even allow me to click the button to open the class.

this might also be a code mistake on my end but take a look and see if it works.

**Comment by sesemaya** [comment]
Hi @loonix 

Little can be gathered from these screenshots. If you can set up a live demo of the issue with JSBin or similar, that would be much more helpful.
