### ISSUE TITLE
I'm newbie. There aren't waves (ripples effect) on buttons and link? Why not?

### ISSUE THREAD

**Issue by johnunclesam** [Daemonite/material#123]
I'm newbie. There aren't waves (ripples effect) on buttons and link? Why not?

**Comment by sesemaya** [comment]
A `.waves-attach` class is required on elements to activate the ripple effect. 

Documentation about ripple effect will be added in [backfilling-bootstrap-v4.0.0-beta](https://github.com/Daemonite/material/tree/backfilling-bootstrap-v4.0.0-beta).

**Comment by johhansantana** [comment]
does the `. waves-attach` class works with current released version?

**Comment by sesemaya** [comment]
@johhansantana yes. for `waves` to work, you need to include `material.js` or `material.min.js` in your html.

**Comment by sesemaya** [comment]
Documentation has been added in a6ef871

**Comment by djibe** [comment]
Plugin is no longer bundled with material.
Get it from here : http://fian.my.id/Waves/#examples

**Comment by sesemaya** [comment]
@adrian-sarmas 

Details regarding this removal are documented here: http://daemonite.github.io/material/docs/4.1/getting-started/migration/#removed-third-party-plugins

**Comment by adrian-sarmas** [comment]
Thanks for help @djibe & @sesemaya
