### ISSUE TITLE
picker.js not in addons

### ISSUE THREAD

**Issue by heatherm** [Daemonite/material#126]
I have a phoenix app where I'm installing daemonite-material via npm and then manually copying over the files under your sass and js directories:

`cp -R node_modules/daemonite-material/assets/sass/ css/material/`
`cp -R node_modules/daemonite-material/assets/js/ js/material/`

I'm using brunch as my build tool and running:

`LOGGY_STACKS=1 node_modules/brunch/bin/brunch build -d` 

I see:
`error: Processing of js/material/addons/pickadate.js failed. Error: Could not load module './picker.js'`

Looks like `require("./picker.js")` is called from pickadate.js, but is not at that path. Does this file exist somewhere or has it been renamed?

**Comment by sesemaya** [comment]
This `require` is part of a third-party JavaScript. It is used in this project as the base of the date picker JavaScript. Once all JavaScript is combined into `material.js`, there will be no `./picker.js` anymore, hence the error occurs. 

I have updated `grunt concat` to remove these `define`s and `require`s from the original JavaScript code when it is being combined into `material.js`.

**Comment by sesemaya** [comment]
Closing as this has been fixed by 6e1d1bf05a53c3d34f9e7ba8ee5bd84e8ba83653
