### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by vucumbra** [Daemonite/material#127]
Hi
i not have understand what is Daemonite material.
Is an extension of Google Material?
This project is active?
thx from a newbie

**Comment by modius** [comment]
> Is an extension of Google Material?

It is a Material styling project for Bootstrap 4 -- see branches for the various releases.

https://v4-alpha.getbootstrap.com/

> This project is active?

Yep. Commits go through every other day. Note these are not necessarily reflected in the **master** branch shown by default on the repo home page.
