### ISSUE TITLE
error on bower install

### ISSUE THREAD

**Issue by donkeyx** [Daemonite/material#129]
Just got a warn on the bower install : 

`> $ bower install daemonite-material#master                                             [±master ●●]
bower not-cached    https://github.com/Daemonite/material.git#master
bower resolve       https://github.com/Daemonite/material.git#master
bower download      https://github.com/Daemonite/material/archive/master.tar.gz
bower extract       daemonite-material#master archive.tar.gz
bower invalid-meta  for:/var/folders/dc/5924lyy90kb_jxyyf727dvfxnhn48k/T/dbinney/bower/6e326da893f9aa910b6f7ec1cd894eee-91209-KnAtS5/bower.json
bower invalid-meta  The "description" is too long, the limit is 140 characters
bower resolved      https://github.com/Daemonite/material.git#08a8d7095d`

**Comment by sesemaya** [comment]
Install latest beta through `bower install daemonite-material#4.0.0-beta`
