### ISSUE TITLE
[question] Material design icons

### ISSUE THREAD

**Issue by devel-pa** [Daemonite/material#13]
Hi, 

Awesome work.

I want to use the material design icons as a separate dependency. What is the source of `_material-design-icons.scss` ?

Thanks

**Comment by sesemaya** [comment]
hi @devel-pa ```_material-design-icon.scss``` is referenced in ```base.scss```. but ```_material-design-icon.scss``` has everything related to material design icons. you can generate a separate material design icon stylesheet just from ```_material-design-icon.scss```

**Comment by devel-pa** [comment]
Thanks, I thought you are using a library like FontAwesome.
