### ISSUE TITLE
Help with carousel buttons

### ISSUE THREAD

**Issue by chromafunk** [Daemonite/material#133]
Hi, I want to make the carousel buttons to look like on hover state by default. If you are using carousel with pictures the buttons won't show if not on hover. This is not practical for certain applicartions. 

Also, is it possible to remove all styles to make the carousel control look like the defaults ? ( white arrows )

Thanks

**Comment by sesemaya** [comment]
Yes. You can change or override any styles applied on carousel buttons to your liking. You can also remove the `carousel-control-nex/prev` classes and then style the buttons completely different.
