### ISSUE TITLE
Bootstrap Beta Is available

### ISSUE THREAD

**Issue by chromafunk** [Daemonite/material#136]
Can we use bootstrap 4 beta without issues with material ?

Just realized it was released 4 days ago.

**Comment by sesemaya** [comment]
Apparently a few changes need to be made. Currently work in progress: `https://github.com/Daemonite/material/tree/backfilling-bootstrap-v4.0.0-beta`.

**Comment by justlevine** [comment]
@sesemaya - how exactly are the "backfilling" branches made?
Is it based on bootstrap 4.0.0 beta, with the Material changes merged on top or is it the base the master Material build, and you're working on integrating the new bootstrap beta changes?

Or, which version do you suggest we use? Is the backfilling branch fully functional as bootstrap, but missing some of that 'material' magic, or are some of the current bootstrap without a fallback?

**Comment by sesemaya** [comment]
@justlevine the current `backfilling-bootstrap-v4.0.0-beta` is almost fully functional as only a couple of things are still missing (i.e. `condensed` and `inverse` table styles). The final beta release will include these styles as well as an improved documentation site. 

If you are not too worried about these particular table styles, then I would suggest to use the beta.

**Comment by sesemaya** [comment]
Beta release has been merged into master: dafde854b331a0eeea136ab12b9062d48adca1ca
