### ISSUE TITLE
.btn-group disable colors

### ISSUE THREAD

**Issue by ztvMark** [Daemonite/material#137]
.btn-group disable colors of buttons and all the buttons look gray
```
.btn-group > .btn, .btn-group-vertical > .btn {
    background-color: transparent;
    bkit-box-shadow: none;
    box-shadow: none;
    -webkit-box-flex: 0;
    -webkit-flex: 0 1 auto;
    -ms-flex: 0 1 auto;
    flex: 0 1 auto;
    min-width: 0;
}
```
If disable background-color: transparent; 
works

**Comment by sesemaya** [comment]
Button group has been restyled by df3ccaba4335abb3a995054c2bc4b4327a6acdec based on the latest Google Material Design Guidelines for toggle buttons: https://material.io/guidelines/components/buttons.html#buttons-toggle-buttons, which is the closest match for Bootstrap button group.
