### ISSUE TITLE
Instructions to build with different colors

### ISSUE THREAD

**Issue by DelBianco** [Daemonite/material#144]
Im trying to rebuild the master with colors changed but i have no idea about the packages this need, im a noob starting to learn sass, and node, have no idea about the packages that i need can someone post here the steps to rebuild it in a linux machine?

**Comment by sesemaya** [comment]
You can do this by modifying `$theme-colors` in `/assets/sass/variables/_palette.scss` and then recompile by running `grunt`

**Comment by DelBianco** [comment]
Thank you.

i did it but first i needed run those commands:
install npm
install grunt 
install sass (i realise that was not installed in this machine)

`sudo apt install npm`
`sudo PATH="$PATH:/usr/local/bin" npm install -g grunt-cli`
`sudo apt install ruby-sass`

so now i can change the colors and run grunt to recompile

hope i can help this project in future.

Thanks for the great work

**Comment by sesemaya** [comment]
Details about "Theming" and "Tooling" are added to the latest documentation.
