### ISSUE TITLE
Desktop viewport hover state transitions would be nice to have

### ISSUE THREAD

**Issue by iamdtms** [Daemonite/material#147]
For example **transition: all .8s ease;** at Carousel, etc.
Preview: https://drive.google.com/open?id=0B1FX0XEAgwyRSHYxSF9GS3d6OG8

**Comment by iamtamasdohany** [comment]
Form component inputs has the same issue. 
Some UX review needed where transitions can be insert in a proper way.

**Comment by sesemaya** [comment]
Regarding adding transition to carousel controls, this is not something we can do at this moment. If added, Webkit will cancel the carousel animation if you trip this while in the middle of another animation.

**Comment by sesemaya** [comment]
Regarding adding transitions for `.form-control`s, this is not something we can do, either. Currently the 2px border applied on `:focus` and `:hover` is actually achieved using `box-shadow` so we don't need to modify the `padding` to compensate potential `border` changes. However transitioning the `box-shadow` doesn't work well in Firefox. Feel free to test it on http://daemonite.github.io/material/docs/4.0/components/forms/ in Firefox by adding `transition` via dev tools. If someone can come up with a fix for the Firefox issue, I'm more than happy to add `transition` on `.form-control`s

**Comment by iamtamasdohany** [comment]
Thank you!
