### ISSUE TITLE
Bootstrap 4v2, pointer cursor and Paypal donation

### ISSUE THREAD

**Issue by djibe** [Daemonite/material#148]
Hi guys,
1) you are awesome, thank you for your work !!!
I'd like to send you some money to get you a beer ! Do you have a Paypal account for donation ?

2) Do you plan a build with bootstrap 4 beta 2 ?

3) What do you think of using pointer: cursor on btn and checkbox elements ?

4) What do you think of MDBootstrap z-index classes ? It's a cool feature.

Thanks for all.
Hope I'll have some time to bring you some work soon.

**Comment by sesemaya** [comment]
Hi @djibe,

[`backfilling-bootstrap-v4.0.0-beta.2`](https://github.com/Daemonite/material/tree/backfilling-bootstrap-v4.0.0-beta.2) is work in progress

**Comment by sesemaya** [comment]
Regarding `pointer: cursor;`, there was a debate over at https://github.com/twbs/bootstrap/pull/21812, since Material design guidelines don't have specific rules regarding this, this project will adhere to Bootstrap. You can always change/override this rule easily in your custom build/CSS.

**Comment by djibe** [comment]
Thank you very much.

Last question, when I try to empty a textarea with floating label, like this  <textarea class="form-control textarea-autosize" id="exampleTextarea1" rows="1"></textarea>
$('#exampleTextarea1').val('') clears textarea but label is still floating.
Same with .val(null) or removeAttr('value') or prop('value', '').
Any idea ??? Thx

**Comment by sesemaya** [comment]
The floating label JavaScript listens to the `change` event and `.val()` doesn't fire that, so in your case, you need to call floating label JavaScript manually after the value is changed, something like: `$('#exampleTextarea1').val('').floatinglabel();`

**Comment by djibe** [comment]
You are the best. Maybe it could be cool to precise it in the doc so noone else burdens you again :-)
Sorry to disturb you.
Love Daemonite !

**Comment by djibe** [comment]
BS4 beta 3 is online ;-)

**Comment by sesemaya** [comment]
@djibe It looks like BS4 beta 3 also reintroduces `cursor: pointer` on certain elements. I've updated Material accordingly: 71cf9f4f662966ff4777a3f50913228e6fb3dc38

**Comment by djibe** [comment]
Thanks for all Maya
