### ISSUE TITLE
Angualr JS Support

### ISSUE THREAD

**Issue by franklloydteh** [Daemonite/material#15]
Would you be interested to create an angularized version of this template? There is already an angular version for the bootstrap.js https://angular-ui.github.io/bootstrap/

There is an ongoing project for angular material design :
https://github.com/angular/material
However this is based on FlexBox instead of Bootstrap.

**Comment by remicastaing** [comment]
What about forking this repo and striping jquery? We could win up to half of the size of the `base.min.js`file. That would be great!

**Comment by athmangude** [comment]
You should check out Angular Material https://material.angularjs.org/

**Comment by remicastaing** [comment]
I already checked it but wasn't completely happy with it.

**Comment by vikashvverma** [comment]
https://material.angularjs.org/ is in development mode and the latest release 0.9.7 seems to have many issues.

**Comment by sesemaya** [comment]
there is no plan to add angular support at this moment

> What about forking this repo and striping jquery out? @remicastaing 

i have noticed this issue and jquery has been separated from material's base js in the latest commit.

**Comment by remicastaing** [comment]
I'm trying to remove jQuery and replace it by angular directive. But it will have to be a separate project and not a new feature for this one. I will share as soon as there is something to be see.
