### ISSUE TITLE
Argument `$map` of `map-get($map, $key)` must be a map

### ISSUE THREAD

**Issue by jalilzade** [Daemonite/material#152]
Hi, After adding importing following scss 

`    @import "~daemonite-material/assets/sass/colours";` 
 `    @import "~daemonite-material/assets/sass/variables";` 

following error happens.

> ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/sass-load
er/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/styles.scss
Module build failed:
undefined
                             ^
      Argument `$map` of `map-get($map, $key)` must be a map
Backtrace:
        node_modules/daemonite-material/assets/sass/variables/_variable-bootstrap.scss:110, in function `map-get`
        node_modules/daemonite-material/assets/sass/variables/_variable-bootstrap.scss:110
      in XXXX\node_modules\daemonite-material\assets\sass\variables\_variab
le-bootstrap.scss (line 110, column 31)

This is line 110 

`$form-feedback-invalid-color: map-get(theme-color(danger), color) !default;`  

when I change this line to 

`$form-feedback-invalid-color: $material-color-red-500 !default;`

problem will be solved. what is wrong with this??

**Comment by sesemaya** [comment]
Can't reproduce. How did you compile your sass? Did you import `functions`?

**Comment by jalilzade** [comment]
I am using via angular-cli 1.5.0, angular 5.0.0 , material 5.0.0-rc0, Yes I have import `functions`.
I am importing in following order.

```
    @import "~daemonite-material/assets/sass/mixins";
     . . . 
    @import "~daemonite-material/assets/sass/colours";
    @import "~daemonite-material/assets/sass/variables";
    @import "~daemonite-material/assets/sass/functions";
    @import "~daemonite-material/assets/sass/print";
    . . .
    @import "~daemonite-material/assets/sass/base/base";
    @import "~daemonite-material/assets/sass/base/grid";
    @import "~daemonite-material/assets/sass/base/typography";
    . . .
    @import "~daemonite-material/assets/sass/bootstrap/alert";
    @import "~daemonite-material/assets/sass/bootstrap/breadcrumb";
    @import "~daemonite-material/assets/sass/bootstrap/badge";    
    @import "~daemonite-material/assets/sass/bootstrap/carousel";
    @import "~daemonite-material/assets/sass/bootstrap/close";
    @import "~daemonite-material/assets/sass/bootstrap/code";
    @import "~daemonite-material/assets/sass/bootstrap/custom-form";
    @import "~daemonite-material/assets/sass/bootstrap/form";
    @import "~daemonite-material/assets/sass/bootstrap/image";
    @import "~daemonite-material/assets/sass/bootstrap/jumbotron";
    @import "~daemonite-material/assets/sass/bootstrap/media";
    @import "~daemonite-material/assets/sass/bootstrap/nav";
    @import "~daemonite-material/assets/sass/bootstrap/pagination";
    @import "~daemonite-material/assets/sass/bootstrap/popover";
    @import "~daemonite-material/assets/sass/bootstrap/responsive-embed";
    @import "~daemonite-material/assets/sass/bootstrap/transition";
    . . .
    @import "~daemonite-material/assets/sass/material";
    . . .
    @import "~daemonite-material/assets/sass/utilities";
```
when trying to build the project getting that error.

**Comment by sesemaya** [comment]
`functions` should come before `variables`

**Comment by jalilzade** [comment]
It is solved. Thanks for support.
