### ISSUE TITLE
Floating label in input when input loaded with predefined value

### ISSUE THREAD

**Issue by rjd22** [Daemonite/material#156]
When loading a input that has a floating label with a predefined value the floating label doesn't automaticly end up on top like you expect it would but ends up into the text area resulting in the following:
![screenshot from 2017-12-13 11-45-00](https://user-images.githubusercontent.com/160743/33935136-29c873d0-dffb-11e7-882a-da71f5b8cffd.png)

The reason this is happening is because Daemonite doesn't seem check if the the field already has an value on initialize but only when on change a `has-value` class is assigned. Checking this manually and assigning the `has-value` manually fixes this issue but I would expect Daemonite to do this.

**Comment by sesemaya** [comment]
This is opt-in for performance reasons, so you need to initialise it yourself.

See: http://daemonite.github.io/material/docs/4.0/material/text-fields/#usage.

It is recommended to run the following JavaScript code after the document is ready or a floating label text field is added dynamically on a page, so the floating label will get the correct initial state based on whether a particular floating label text field has value or not.

```
$('.floating-label > .form-control').floatinglabel();
```
