### ISSUE TITLE
Running `npm install` results in daemonite having it's own node_modules directory

### ISSUE THREAD

**Issue by rjd22** [Daemonite/material#160]
We're having a odd bug with npm installing daemonite resulting the package directory in node_modules having it's own node_modules.

![screenshot from 2017-12-29 16-25-09](https://user-images.githubusercontent.com/160743/34440358-026f31d6-ecb5-11e7-89e4-9b57454a0e8b.png)

This makes Deamonite not usable in combination with webpack as it results in multiple versions of jQuery being packaged.

I'm not sure what setting is causing this. But it only happens with the deamonite-material package.

reproduce by doing:
```
npm init
npm install daemonite-material@^4.0.0-beta
```

**Comment by sesemaya** [comment]
Probably a bug in `package.json` file. This should have been fixed in the latest version though. Please re-open if you still encounter the same problem with `backfilling-bootstrap-v4.0.0`.

**Comment by rjd22** [comment]
@sesemaya would it be possible to release a beta2 that fixes this bug?

**Comment by sesemaya** [comment]
@rjd22 `v4.0.0` was just released
