### ISSUE TITLE
Screen sizes not corresponding to BS4

### ISSUE THREAD

**Issue by djibe** [Daemonite/material#161]
Hi guys,
I discovered last night that Material uses min-width: 1280px for large and min-width: 1920px for xlarge.

Why doesn't it stick to BS4 standards ? 992px for large and 1200px for xl ?

Thanks a lot for your help.

**Comment by sesemaya** [comment]
Hi @djibe 

The breakpoints and container's max widths are based on Material Design specs: https://material.io/guidelines/layout/responsive-ui.html#responsive-ui-breakpoints.

Material recommends that

> interfaces should adapt layouts for the following breakpoint widths: 480, 600, 840, 960, 1280, 1440, and 1600dp

However, Bootstrap only has 4 breakpoints by default, so I have to select a few from the Material specs based on the information provided on the page linked above.

**Comment by djibe** [comment]
Hi, thanks again.
Yes I know about MD specs about screen sizes but I thought you wanted to keep the full BS4 compatibility. So any project can come to Daemonite and leave Daemonite without having breakpoints errors.
Thanks for all.

**Comment by sesemaya** [comment]
Not sure if Material Design breakpoints work well, especially the `lg` and `xl` ones.
I may change this project's breakpoints back to inheriting BS4 values by default.

**Comment by djibe** [comment]
That's what I feel in my recent day to day usage.
Thx
