### ISSUE TITLE
Upgrading from v4-beta to V4-release

### ISSUE THREAD

**Issue by justlevine** [Daemonite/material#165]
Hi,
What's the upgrade path from v4-beta to V4-release?
Is it enough to follow Bootstrap's migration path (e.g. https://getbootstrap.com/docs/4.0/migration/#beta-3-changes ) or have there been material-specific changes as well that we need to account for?

**Comment by sesemaya** [comment]
Please follow Bootstrap's migration path. The majority of the recent changes in this project is to get the code in line with Bootstrap's changes.

Feel free to reopen this issue if you have any other questions or if I have missed anything.

**Comment by sesemaya** [comment]
A migration doc is on  the way: #167
