### ISSUE TITLE
Create a migration doc covering changes from `alpha` & `beta` to stable v4

### ISSUE THREAD

**Issue by sesemaya** [Daemonite/material#167]
Document the breaking and the most notable changes for people who update Material to stable v4 from `alpha` or `beta`:

- [x] FAB with dropdown menu
- [x] Navigation drawer variations with responsive behaviours
- [x] Textarea auto resize removed
- [x] Waves removed

**Comment by djibe** [comment]
Thanks.

**Comment by djibe** [comment]
Textarea autosize is here ;-) https://jsfiddle.net/djibe89/bofcrp8v/

**Comment by sesemaya** [comment]
Migration doc: http://daemonite.github.io/material/docs/4.1/getting-started/migration/
