### ISSUE TITLE
Roboto font is missing in css/fonts

### ISSUE THREAD

**Issue by nogo** [Daemonite/material#17]
Its really nice you remove the font downloading from google, but now the roboto font is missing in css/font.

**Comment by sesemaya** [comment]
@nogo roboto font is still loaded from google font, but it is now loaded using web font loader javascript instead of an @import in css

**Comment by nogo** [comment]
@sesemaya too bad i'm not using the javascript at all. So I have to do it on my own. Thanks for the reply.
