### ISSUE TITLE
PickaDate IE 11 & edge

### ISSUE THREAD

**Issue by bobebia** [Daemonite/material#171]
Testing my application on different browsers I noticed that the pickaDate on Opera, Firefox and Chrome works perfectly, while on IE 11 and Edge very often when you close the calendar reopens automatically and never closes.
Can you close it only with the 'ESC' key.

does anyone find my same problem?

tnks

**Comment by sesemaya** [comment]
Although I couldn't reproduce the exactly same problem, I have come across quite a few similar issues with picker in IE. ac2c475 and dbf6d9e addressed these problems. Can you please test if these changes also fix your problem.
