### ISSUE TITLE
Example pages

### ISSUE THREAD

**Issue by nasirkhan** [Daemonite/material#172]
Thanks for developing this wonderful theme. I really liked it a lot. 

I have a query that do you have any example page created here or somewhere else. I was that almost all the components are documented and by using those admin dashboard or website designed can be created. But if there is any example page it would be helpful for new users.

**Comment by sesemaya** [comment]
Hi @nasirkhan,

Please feel free to check http://daemonite.github.io/material/docs/4.1/getting-started/introduction/
