### ISSUE TITLE
btn-group-fluid class missing in documentation

### ISSUE THREAD

**Issue by djibe** [Daemonite/material#174]
Hi Maya,
just to report that the .btn-group-fluid class is missing from the documentation.

I gonna take a MOOC on Github to propose Pull requests instead of bothering you.

Thanks for all.

**Comment by sesemaya** [comment]
`.btn-group-fluid` is already covered in http://daemonite.github.io/material/docs/4.0/material/buttons/#toggle-buttons (scroll past the first two examples in this section).

**Comment by djibe** [comment]
Sorry for this mistake. I couldn't find it again.
Should get some sleep.
Thx for all Maya
