### ISSUE TITLE
Snackbars

### ISSUE THREAD

**Issue by djibe** [Daemonite/material#176]
Hi Maya,
I am working on the implementation of Bootstrap Notify for your material kit.
Here is the start of the fiddle : https://jsfiddle.net/djibe89/5hw6ktkk/
Here is the full doc for the plugin : http://bootstrap-notify.remabledesigns.com/

Could you change the alert-dark to #323232 ? (I don't know which file to commit).
According to https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-specs

I am collecting all components for your kit, here we are : https://github.com/djibe/Bootstrap-4-Advanced-Components/

Thanks for all, as usual

**Comment by sesemaya** [comment]
`4.1` will add snackbars. Related code currently in `v4-dev` branch: https://github.com/Daemonite/material/blob/v4-dev/assets/scss/material/_snackbar.scss
