### ISSUE TITLE
Does material work with full version of jQuery?

### ISSUE THREAD

**Issue by adrian-sarmas** [Daemonite/material#179]
I need the full version of jQuery for a project so I'm using `https://code.jquery.com/jquery-3.2.1.min.js` instead of `https://code.jquery.com/jquery-3.2.1.slim.min.js`. I've noticed issues with the Expansion panels ([http://daemonite.github.io/material/docs/4.0/material/expansion-panels/](http://daemonite.github.io/material/docs/4.0/material/expansion-panels/)). It has a extra timeout on the first open and the collapsible up/down arrow icon stop updating after a couple of open/close actions. If I use the slim version of jQuery it works properly. Do you test using the full version of jQuery or just the slim version?

**Comment by sesemaya** [comment]
Confirming that there indeed is a timeout on the first open with `3.2.1`, but it works thereafter no matter how many actions are performed. I'll take a look at this issue.

The JavaScript works with the full version and is tested with `3.3.1`, so in the meantime maybe you can try update to `3.3.1` before I fix this.

**Comment by adrian-sarmas** [comment]
I've tried with `https://code.jquery.com/jquery-3.3.1.min.js` and I still have the same issue.
Please have a look at this: 
https://monosnap.com/file/qJOXpo6R3UYMTKVxyAOyuBrbV9X9VQ
There is also an issue with the arrow icons. The up arrow is shown all the time after a few open/close actions.

**Comment by sesemaya** [comment]
Hi @adrian-sarmas,

If you can set up a live CodePen or a JS Bin that would help a lot.

Meanwhile, can you please make sure that you have either 1) removed jQuery's `crossorigin` and `integrity` or 2) updated their values? The `hash` values from the documentation pages are paired with `3.3.1.slim` version. Additionally, please make sure you have updated `bootstrap.js` to version 4.1.0.

**Comment by adrian-sarmas** [comment]
I've tried in a codepen with the `https://code.jquery.com/jquery-3.3.1.min.js` version and `4.1.0` version of bootstrap and i see no issues there. I guess there are some issues in my project that I need to track down.
