### ISSUE TITLE
Pull request?

### ISSUE THREAD

**Issue by j-norwood-young** [Daemonite/material#18]
Hi there

I sent a pull request 21 days ago, but you haven't responded. I don't mind if you reject it, or request that I change it, but would appreciate a response. If you don't want pull requests, maybe mention it in your readme.

**Comment by dandv** [comment]
Has this ever received a response?

**Comment by modius** [comment]
This pull request was refused on account of duplicating existing work; 
[#11 Progress bars](https://github.com/Daemonite/material/pull/11)
