### ISSUE TITLE
Select 2 compilation

### ISSUE THREAD

**Issue by djibe** [Daemonite/material#184]
Hi Maya, I am trying to compile SCSS of Select2 Bootstrap 4 theme from  this repository https://github.com/berkan52/select2-bootstrap4-theme/tree/master/src
It works with vanilla BS 4.1.
But I fail to make it work with material.
Could you look briefly at it ?

Thanks for all your updated.
djibe

**Comment by sesemaya** [comment]
Some variables in Material are named differently, that is why this fails to compile with Material.

**Comment by djibe** [comment]
I'll try to dig in material to find the variables.
Thx again.
I still need your Paypal login to send you some money Maya !
