### ISSUE TITLE
Prepend on input?

### ISSUE THREAD

**Issue by MACscr** [Daemonite/material#185]
Seems input-group isnt supported by this repo, thus I cant use 	something like:				

`<span class="input-group-addon">$</span>`

whats the proper way to prepend on input with your material package?

**Comment by sesemaya** [comment]
Hi @MACscr 

Input group is fully supported. Please refer to http://daemonite.github.io/material/docs/4.1/components/input-group/#basic-example for examples.

Please be aware that BS4 rewrote `.input-group` in https://github.com/twbs/bootstrap/pull/25020. One of the many changes is that it dropped `.input-group-addon` class for `.input-group-append/prepend`.
