### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by braginteractive** [Daemonite/material#19]
any plans to make a bower package?

**Comment by devel-pa** [comment]
@sesemaya  Hi, are you interested in a pull request related to "bowerification"?

**Comment by sesemaya** [comment]
@devel-pa hi, that will be appreciated

**Comment by sesemaya** [comment]
registered as a bower package: daemonite-material in commit https://github.com/Daemonite/material/commit/405ed75f00c1f629e8fb0bd1cc4a2c132622d049
