### ISSUE TITLE
Docs has 404s form https://getbootstrap.com/assets/css/docs ....

### ISSUE THREAD

**Issue by andreaswarnaar** [Daemonite/material#190]
Hi ,

I noticed that some errors in the dev console. 
it seems that the resources from https://getbootstrap.com/assets are no longer available to include into remote pages.

**Comment by sesemaya** [comment]
Hi @andreaswarnaar,

Bootstrap's `docs.css` and `docs.js` are now versioned too, so the `https://getbootstrap.com/assets` URLs no longer work. This issue has been addressed in [`v4.1.1`](https://github.com/Daemonite/material/commit/ad4101f870d137e5b15fab41ee767a65ee838e90#diff-aeb42283af8ef8e9da40ededd3ae2ab2).
