### ISSUE TITLE
Select not displaying properly

### ISSUE THREAD

**Issue by ayouboudelaa** [Daemonite/material#191]
Using form-control class on select field causes the following display:
![1](https://user-images.githubusercontent.com/16936149/40585684-4a3c8654-61b7-11e8-90c5-d1100bdc8ff6.png)
As you can see there are two select arrows, the native one and the material one.
Browser: Chrome 66.0.

**Comment by djibe** [comment]
@ayouboudelaa Are you declaring Bootstrap CSS ?
Must be cause I never experience this in Chromme 66
Juste declare material.css

**Comment by ayouboudelaa** [comment]
I figured it out and it is weird. When I import the CSS file (material.css), it works fine. However, when I import the SCSS file (material.scss), it produces the issue, isn't the CSS file just a compiled version of the SCSS ? Because in my case, I need to modify some variables, so I perefer using SCSS version.

**Comment by sesemaya** [comment]
@ayouboudelaa 

`material.css` is a compiled version of `material.scss` and a bit more: http://daemonite.github.io/material/docs/4.1/getting-started/tooling/#postcss, so once you have modified the variables, make sure to re-compile the CSS and see if the issue goes away.

**Comment by ayouboudelaa** [comment]
@sesemaya Thanks for the hint. I'm using Webpack, so the SCSS is actually compiled to CSS. However, when you said "and a bit more", I guess you meant something like autoprefixing, and it is the case !, my Webpack configuration misses postCSS and autoprefixer, adding them should fix the issue.
