### ISSUE TITLE
Bootstrap Select available

### ISSUE THREAD

**Issue by djibe** [Daemonite/material#194]
Hi Maya,
just to share that I coded a material theme for Bbootstrap Sselect ccompatible with your awesome material UI, play here : https://jsfiddle.net/djibe89/yvbts5e9/

**Comment by vaishnavmhetre** [comment]
@djibe, I've added reveal from right (experimental) feature to the dropdown menu you've designed to be included. Please take a look and refine if possible.

Additionally add reveal direction (I've hard coded top right) to be easy for the select box. For additional customization options regarding material menus(dropdowns), refer Angular Material Menu Component.
