### ISSUE TITLE
Navigation drawer hidden behind toolbar

### ISSUE THREAD

**Issue by jjoseba** [Daemonite/material#202]
When using a toolbar with `.sticky-top` or `.fixed-top` class in combination with a navigation drawer using `.navbardrawer-permanent`, the drawer shows up behind the toolbar, hidding its top part. It is a problem with the `.navbardrawer-permanent` class `z-index` (it is set to `auto`).
In my case I fixed it making a rule that modifies this `z-index`, but I'm not sure if it would apply to all the navigation drawer cases...

**Comment by sesemaya** [comment]
Hi @jjoseba,

This depends on how the navbar is intended to work.

With your fix, the navigation drawer will cover the left part of the toolbar, which itself may also be an issue.

The permanent navigation drawer is supposed to push the toolbar to the right/left like the rest of the page.

![Screen Shot 2020-01-08 at 12 29 10 pm](https://user-images.githubusercontent.com/1403640/71942809-86c3cb00-3212-11ea-96e5-3eb2f98affc1.png)

> Because a permanent navigation drawer is always visible, you may need to add some custom styles to shift the content of your page to the left or right to accommodate the screen estate being taken up by the drawer.

**Comment by gismofx** [comment]
@sesemaya Thanks for providing that answer and style example. Can those custom styles be added into the main CSS? Short term, How do I add that custom style you shared above? Can it be in a separate file?
