### ISSUE TITLE
have a language package?

### ISSUE THREAD

**Issue by DevaloperHH** [Daemonite/material#203]
I want to translate datepiker components

**Comment by djibe** [comment]
Hi, 
- you can download my fork : https://djibe.github.io/material/docs/4.4/getting-started/introduction/, download `source code download` link and unzip files
- Now go to assets/js/src/pickdate.js
- Go to line 77 to change months names  
`monthsFull       : ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],`
- Save file
- Now open terminal and type command : `npm run js`
- New compiled JS will be in /js folder.

**Comment by DevaloperHH** [comment]
> Hi,
> 
> * you can download my fork : https://djibe.github.io/material/docs/4.4/getting-started/introduction/, download `source code download` link and unzip files
> * Now go to assets/js/src/pickdate.js
> * Go to line 77 to change months names
>   `monthsFull       : ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],`
> * Save file
> * Now open terminal and type command : `npm run js`
> * New compiled JS will be in /js folder.

Hi,Thank you for your reply😁
