### ISSUE TITLE
Label overlapping in text area

### ISSUE THREAD

**Issue by kushal9291** [Daemonite/material#205]
There is problem with floating label in text area field. It gets overlapped with text. here is the screenshot.
![textareabug](https://user-images.githubusercontent.com/16516005/47566077-2cf61e80-d948-11e8-9c36-873c668ab2af.png)

**Comment by d-bourdon** [comment]
a quick fix:

```
/* CSS style */
.floating-label.textfield-box textarea {
    padding-top: 0 !important;
    border-top: solid #f0f0f0 1.5rem !important;
}
.floating-label.textfield-box label {
   z-index: 1;
}
```

The border-top need to be set to the same background-color that the textarea

**Comment by kushal9291** [comment]
> a quick fix:
> 
> ```
> /* CSS style */
> .floating-label.textfield-box textarea {
>     padding-top: 0 !important;
>     border-top: solid #f0f0f0 1.5rem !important;
> }
> .floating-label.textfield-box label {
>    z-index: 1;
> }
> ```
> The border-top need to be set to the same background-color that the textarea

I used a different solution. But this one is better.
