### ISSUE TITLE
How can i use the fbtn-inner as a toggle to control the menu open and close?

### ISSUE THREAD

**Issue by samws32** [Daemonite/material#21]
It will be appreciated if you can offer a detail code.
I am totally new to Javascript.

thanks for your help.
have a nice day.
:)

**Comment by sesemaya** [comment]
@samws32 just add '.menu-toggle' class on the floating action button (i.e. '.fbtn'), and a 'data-target' or 'href' pointing to the menu. no other changes are required.

**Comment by samws32** [comment]
thanks to your reply.:-)
shall update the codes with a303858？

**Comment by sesemaya** [comment]
@samws32 yes
