### ISSUE TITLE
Datepicker issue on Chorme v.73

### ISSUE THREAD

**Issue by karlokukavicic** [Daemonite/material#214]
Hi,
with the last Chrome update, the datepicker modal doesn't work anymore (the modal open and immediately close itself).

**Comment by djibe** [comment]
https://github.com/Daemonite/material/issues/214

**Comment by Crick87** [comment]
Here the same. I hope it could be fix soon.

**Comment by SullivanPro** [comment]
do you have any news about this bug?

**Comment by djibe** [comment]
Works perfectly on latest Firefox. But don't know how to investigate this.

**Comment by agrothe** [comment]
Also noticed this bug in Chrome since the last update. 

Here is a minimal reproduction: [](https://output.jsbin.com/duxiqez)

**Comment by djibe** [comment]
It works for me with this modif 

line 898
// Bind the document events.
$document.on( 'click.' + STATE.id + ' focusin.' + STATE.id, function( event ) {

replaced by
$document.on( 'click' + STATE.id + ' focusin' + STATE.id, function( event ) {

Does it for you ?
I yes, I'll create a pull request

**Comment by Crick87** [comment]
@djibe You rock!! :D 
Thanks!!!! It works!!!

**Comment by djibe** [comment]
Glad to help.
I'll subit a PR next weekend

**Comment by SullivanPro** [comment]
@djibe I've correct my code and it works ! Thx :D

**Comment by karlokukavicic** [comment]
@djibe Thanks!!! :)

**Comment by sesemaya** [comment]
Hi all, this seems to be fixed after I updated `devDependencies` (e12c586ba2883132330f0faebba022c2c04fe38d). The latest changes are in `master` now and I am not able to reproduce this issue anymore.

Please feel free to reopen this if you still have issues with date picker after this update.

**Comment by djibe** [comment]
@sesemaya 
The example in the documentation http://daemonite.github.io/material/docs/4.1/material/pickers/ still doesn't work in Chrome 73.
Is the documentation calling an outdated lib ?
Or the bug is not yet fixed ?

**Comment by djibe** [comment]
Ok my fault, it works perfectly now.
Thx Maya. Once again

**Comment by dantheother** [comment]
So, how does one get this working when using the npm version? Stop using 4.1.1 from NPM and... something?

**Comment by HuzaifaSaifuddin** [comment]
Facing same issue with Chrome, Using gem
gem 'material-sass', '4.1.1'
gem 'bootstrap',     '4.1.1'

**Comment by djibe** [comment]
Hi, you must use my fork now were pickers are fixed : https://djibe.github.io/material/docs/4.4/material/pickers/
