### ISSUE TITLE
It there a cdn for this? I tried to do an email template with this and message got clipped...

### ISSUE THREAD

**Issue by arivera12** [Daemonite/material#217]

**Comment by djibe** [comment]
Sorry, can you detail your problem ?

**Comment by arivera12** [comment]
I pasted the css file for creating a email template and after 102 kb message got clipped on the email client. I can reference the stylesheet from my server but I was willing to reference it from cdn.

**Comment by djibe** [comment]
Best CDN place : JS Delivr https://www.jsdelivr.com/package/npm/daemonite-material

**Comment by arivera12** [comment]
@djibe Thanks!
