### ISSUE TITLE
Autocomplete component

### ISSUE THREAD

**Issue by tezine** [Daemonite/material#218]
Hi, thank you for this excelent project! 
I wonder if you have any plans to create an Autocomplete, similar to this one: https://material.angular.io/components/autocomplete/examples 
This would be awesome!

**Comment by djibe** [comment]
Hi, you can try this : https://raw.githack.com/xcash/bootstrap-autocomplete/master/dist/latest/index4.html#

**Comment by sesemaya** [comment]
Hi @tezine,

At this stage, we are not planning to include autocomplete out of the box.

What we did with some of our own projects with autocomplete is to use custom JavaScript just for autocomplete function (e.g. jQuery UI, Select2, etc.) and use Material's dropdown for the styles.
