### ISSUE TITLE
Datepicker broken in chrome

### ISSUE THREAD

**Issue by rpuk-matt** [Daemonite/material#219]
Version 73.0.3683.103 (Official Build) (64-bit)

Click on any date input here http://daemonite.github.io/material/docs/4.1/material/pickers/ and the calendar pops up then immediately hides again.

Works fine in Edge & IE

**Comment by dantheother** [comment]
There's a resolution over on https://github.com/Daemonite/material/issues/214

**Comment by rpuk-matt** [comment]
Using latest js fixes this issue.
