### ISSUE TITLE
Can't normaly use date pickers in Chrome (74.0.3729.131).

### ISSUE THREAD

**Issue by kaanlab** [Daemonite/material#221]
When I click on the date picker field, the modal window appears and then disappears. I can not select a date normaly. I use last material build 4.1.1.

**Comment by djibe** [comment]
Same as https://github.com/Daemonite/material/issues/214 and https://github.com/Daemonite/material/issues/219
Please close Issue.

**Comment by dantheother** [comment]
@djibe I'm not seeing the problem in Chrome 74 if I follow the resolution in #214

**Comment by kaanlab** [comment]
Yes, all work in master branch
