### ISSUE TITLE
Modal is not a function 

### ISSUE THREAD

**Issue by Farham0** [Daemonite/material#227]
When I am trying to open the modal with the following code, I get the error modal is not a function, I am sure I brought the library and I can trigger modal with a button . 

   `$("#testModeal").modal({ show: true });`

**Comment by djibe** [comment]
$("#testModal").modal('show');

**Comment by Farham0** [comment]
Thank you for reference but it does not work 

searchFarsi.js:43 Uncaught TypeError: $(...).modal is not a function
    at initSearch (searchFarsi.js:43)
    at HTMLDocument.<anonymous> (customHomeFa.js:10)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)

**Comment by djibe** [comment]
Add this to your header : <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>

**Comment by djibe** [comment]
@Farham0 
Hi, is your problem solved ?
Can you close this Issue ?

**Comment by sesemaya** [comment]
Close due to lack of activities. Please feel free to reopen with new information.

Thanks @djibe for your help.
