### ISSUE TITLE
Has this project been abandonned?

### ISSUE THREAD

**Issue by halfpastfouram** [Daemonite/material#239]
- Latest commit in master was 7e87b19 on 4 Apr 2019.
- Multiple high priority issues still open with not a single response from @sesemaya or [any other contributor](https://github.com/Daemonite/material/graphs/contributors).
- Dependabot has an open PR: https://github.com/Daemonite/material/pull/236

It seems that @djibe has done an incredible effort of updating this project and has an open PR https://github.com/Daemonite/material/pull/223 that will update the project to Bootstrap's 4.3.1 version with both fixes and improvements.

Please tell us what to expect for this project as a lot of of people seem to be using it and continued support is a must.

**Comment by djibe** [comment]
@halfpastfouram Having no news of @sesemaya , I forked it : https://github.com/djibe/material

You should have all you need there.
Even thought Snackbars and Switches are broken. I'm on it.
Tell me if you have bugs/

Enjoy

**Comment by halfpastfouram** [comment]
I've e-mailed the company that created this project and asked them what they were gonna do with it. I'll let you know if I ever get a reply.

**Comment by sesemaya** [comment]
Hi all we are currently looking to bring this directly to v4.4.1.
