### ISSUE TITLE
Not possible to have link ont left AND right navbar 

### ISSUE THREAD

**Issue by zf-development** [Daemonite/material#247]
I would like to add link like Login & Register to the right of my navbar.

I tried everything I know in CSS and HTML but I haven't been able to do it.

Today I'm asking you to include a possibility to add links to the right of a navbar.

**Comment by djibe** [comment]
Hi, do you have a screenshot of your actual navbar ?
Or a drawing of what you want ?

**Comment by sesemaya** [comment]
@zgagne 

I believe you can achieve this by either

1. Using `.ml-auto` class to push the element to the right:
```
<nav class="navbar ...">
    <ul class="navbar-nav ml-auto">
        ...
    </ul>
</nav>
```
2. If your `.navbar` only contains links on the right hand side, then you can change the alignment of the `.navbar` by adding `.justify-content-end` class:
```
<nav class="navbar justify-content-end ...">
    <ul class="navbar-nav">
        ...
    </ul>
</nav>
```
Hope that helps.

**Comment by zf-development** [comment]
Using .mr-auto was not working so I redownloaded the gem and it’s fixed.
