### ISSUE TITLE
Swipe support

### ISSUE THREAD

**Issue by jpike88** [Daemonite/material#25]
Needs ability to swipe side menus in and out of view

**Comment by andersonid** [comment]
will be awesome for mobile concepts!

On Thu, May 28, 2015 at 4:58 AM, jpike88 <notifications@github.com> wrote:

> Needs ability to swipe side menus in and out of view
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Daemonite/material/issues/25>.
>



-- 
--

*Anderson Nobre*
*Digital Designer*

*nobre@andersonid.com <nobre@andersonid.com>*
*(11) 9.8635.5330 *whatsapp, viber
*andersonid* skype

**Comment by samws32** [comment]
check out issue #21

**Comment by jpike88** [comment]
I've got a workaround.

Download jquery touch swipe and add this script

	$(document).ready(function () {
		
		
		$("body").swipe( {
			swipeRight:function(event, direction, distance, duration, fingerCount) {
         	if($(".menu-right").hasClass("open")){
								$(".right-menu").trigger("click");
							} else {
								$(".left-menu").trigger("click");
							}
        },
        swipeLeft:function(event, direction, distance, duration, fingerCount) {
          	if($(".menu-left").hasClass("open")){
								$(".left-menu").trigger("click");
							} else {
								$(".right-menu").trigger("click");
							}
        },
					  excludedElements:$.fn.swipe.defaults.excludedElements+", .switch",
					  fallbackToMouseEvents:false,
					  maxTimeThreshold:300
					});
		});

**Comment by samws32** [comment]
https://github.com/mattbryson/TouchSwipe-Jquery-Plugin

download touch swipe here? or anyohter addrrss suggested ?

**Comment by jpike88** [comment]
thats the one

**Comment by samws32** [comment]
can not work with the above adding script....

**Comment by jpike88** [comment]
This is a very ugly workaround. 

I should have mentioned that you need to add the classes 'left-menu' and 'right-menu' to the buttons that the user would click.

**Comment by samws32** [comment]
<ul class="nav nav-list pull-left">
			<li>
				<a class="menu-toggle" href="#menu">
					<span class="access-hide">Menu</span>
					<span class="icon icon-menu icon-lg"></span>
					<span class="header-close icon icon-close icon-lg"></span>
				</a>
			</li>
		</ul>
		<a class="header-logo" href="index.php"><i class="fa fa-home"></i></a>
		<ul class="nav nav-list pull-right">
			<li>
				<a class="menu-toggle" href="#search">
					<span class="access-hide">Search</span>
					<span class="icon icon-search icon-lg"></span>
					<span class="header-close icon icon-close icon-lg"></span>
				</a>
			</li>
			<li>
				<a class="menu-toggle" href="#profile">
					<span class="access-hide">John Smith</span>
					<span class="avatar avatar-sm"><img alt="alt text for John Smith avatar" src="images/users/avatar-001.jpg"></span>
					<span class="header-close icon icon-close icon-lg"></span>
				</a>
			</li>
		</ul>


do you mean the menu-toggle?

**Comment by sesemaya** [comment]
this seems to be more like a project specific requirement. if a site has menus on both sides or multiple menus on one side such as the demo pages, it'll be tricky to determine what particular actions to call when a horizontal swipe occurs. 

i'm afraid i'll not be adding "swipe" in material's base js. "swiping menu in and out of view" is also not documented in google material guideline: http://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-behavior
