### ISSUE TITLE
date pickers -> change the language 

### ISSUE THREAD

**Issue by ImhotepDE** [Daemonite/material#251]
Hello,

can I change the language of the date pickers to for example german?

Thanks for the help

**Comment by djibe** [comment]
You can try to change these parameters for a custom translation

labelMonthNext: 'Next month',
          labelMonthPrev: 'Previous month',

          // The title label to use for the dropdown selectors
          labelMonthSelect: 'Select a month',
          labelYearSelect: 'Select a year',

          // Months and weekdays
          monthsFull: [ 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December' ],
          monthsShort: [ 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec' ],
          weekdaysFull: [ 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday' ],
          weekdaysShort: [ 'Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat' ],

          // Today and clear
          today: 'Today',
          clear: 'Clear',
          close: 'Close'

And tell us if you were successful

**Comment by djibe** [comment]
@ImhotepDE Hi, did it work ?

**Comment by ImhotepDE** [comment]
Hi, first of all thanks for the quick response. I didn't try any more, I'm sorry.

I now use the DateTime Picker from: https://github.com/T00rk/bootstrap-material-datetimepicker

It has all the necessary functions like time and date.

**Comment by djibe** [comment]
@ImhotepDE I did a fork for this plugin with updated styles.
I'll update it again soon.
