### ISSUE TITLE
djibe fork

### ISSUE THREAD

**Issue by stsrki** [Daemonite/material#254]
Hi @djibe 

Sorry I had to open ticket here. You don't have or maybe you have disabled issues on your fork.

- What is the long-term plan for your forked project?
- Are you going to merge it here after it's finished?
- Do you plan to enable issues on your project page?

Unfortunately creators of this fork as it currently stands seems to have abandon the project. So it's pretty unclear what the users are going to do next.

**Comment by djibe** [comment]
Hi,

- I use it for all my projects so I maintain it but it is open source so anyone can take over.  
I normaly will maintain it after it has the quality I want
- I hope @sesemaya will one day "unite them all" :D  
I cannot merge here, we need Daemonite team to do it.
- Oooops. I didn't notice Issues were not activated on my fork. It is fixed  
I am working on material design Lists now. Finishing checkbox integration.

**Comment by djibe** [comment]
My fork is here https://github.com/djibe/material

Nearly running Bootstrap 4.5.0

**Comment by djibe** [comment]
Running Bootstrap 4.5 : https://djibe.github.io/material/docs/4.5/material/buttons/

**Comment by djibe** [comment]
@stsrki Hi, maybe you can close this issue.
By the way 4.5.3-rc2 is out with new rangeslider: https://djibe.github.io/material/docs/4.5/plugins/sliders-ionrangeslider/

**Comment by stsrki** [comment]
The new range slider looks great! Thank you!
