### ISSUE TITLE
Error when loading the js file!

### ISSUE THREAD

**Issue by zalnaRs** [Daemonite/material#263]
Uncaught TypeError: (intermediate value)(intermediate value) is not a function
    at expansion-panel.js:49
    at material.min.js:6
    at material.min.js:6

**Comment by zalnaRs** [comment]
My code: 
My code:
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>a</title>
    <link rel="stylesheet" href="../assets/css/main.css">
    <link rel="stylesheet" href="../assets/material/material.min.css">

</head>
<body><script src="../assets/material/material.min.js" /></body>

**Comment by djibe** [comment]
Hi, what happens if you use dependencies from my fork ?

https://djibe.github.io/material/docs/4.5/getting-started/introduction/#starter-template

**Comment by zalnaRs** [comment]
> Hi, what happens if you use dependencies from my fork ?
> 
> https://djibe.github.io/material/docs/4.5/getting-started/introduction/#starter-template

Its works with your version idk what you changed :)
