### ISSUE TITLE
Stop supporting IE 8 and 9

### ISSUE THREAD

**Issue by obsidienne** [Daemonite/material#30]
Those versions of IE are not used enough for the amount of work needed to support them

**Comment by dandv** [comment]
:+1:

This would also enable removing some old vendor prefixes, e.g. [for flex](https://github.com/Daemonite/material/blob/4c3de9ade6f5e6c67b1bf4d8f0e0d073fbee8387/css/base.css#L5226.

**Comment by Ugarz** [comment]
:+1:  I upvote for it too, because of the future of Windows 10 who's trying to establish a new use of Microsoft Edge.

**Comment by dandv** [comment]
See also http://github.hubspot.com/tether/overview/why_we_dont_support_ie_8/

**Comment by mackelito** [comment]
+1

**Comment by sesemaya** [comment]
support for old browsers has been removed in this commit: https://github.com/Daemonite/material/commit/94917803afdcab902789ff3dfacda469aca4e800
