### ISSUE TITLE
How do I add tabs in the header?

### ISSUE THREAD

**Issue by anidotnet** [Daemonite/material#32]
There are several material design mobile apps which have tab in the header area like whats-app, google reader etc. But here in this framework, I can't add tabs into the header area satisfactorily. (I am not a css wiz though). Can you please show me how to achieve that?

**Comment by sesemaya** [comment]
@anidotnet please see `ui-tab.html

**Comment by anidotnet** [comment]
Thanks. But how do I add it in the middle of the header like the below? Moreover, in ui-tabs the search is gone. I want to keep the header like other pages (with right menu and left menu) and add tabs like below. How can I do that? Thanks in advance.

![screenshot_2015-06-10-08-27-34](https://cloud.githubusercontent.com/assets/696662/8074056/c9a88ffe-0f4a-11e5-8cdb-ed309f88ba4d.png)
