### ISSUE TITLE
Create releases

### ISSUE THREAD

**Issue by obsidienne** [Daemonite/material#36]
Hi, 

In order to help people get stable releases of material. Could you please create [release](https://help.github.com/articles/about-releases/). Like [leaflet](https://github.com/Leaflet/Leaflet/releases)

It's not time consuming but can help a lot.

Thanks

**Comment by dandv** [comment]
:

**Comment by modius** [comment]
Thanks.  We've started a semi-regular release cycle:
https://github.com/Daemonite/material/releases
