### ISSUE TITLE
Add animated bottom border to input boxes

### ISSUE THREAD

**Issue by dandv** [Daemonite/material#47]
[Polymer Paper](https://www.polymer-project.org/0.5/components/paper-input/demo.html) implements this.

One method: http://jsfiddle.net/muicss/Lrw1me3e/

Would love to see this at:
http://daemonite.github.io/material/docs/4.0/components/forms/

**Comment by sesemaya** [comment]
This will require some additional HTML markup compared to default Bootstrap. Such as 
```<span class="bar"></span>``` in your example. 

Additionally, the example in Material Design Guideline does not have this animation: https://material.google.com/components/text-fields.html#text-fields-required-fields.

**Comment by sesemaya** [comment]
Close as a dupe of #147
