### ISSUE TITLE
Comparison with alternative Material projects; eg. MaterializeCSS

### ISSUE THREAD

**Issue by dandv** [Daemonite/material#50]
From [the commit history](https://github.com/Daemonite/material/commits/master?page=8), I see this library was started in Feb 2015. At that time, [MaterializeCSS](materializecss.com) was already around, so there must've been good reasons to not contribute there instead, or fork that project.

Would be nice to [mention prior art](https://github.com/jagi/meteor-astronomy/issues/27) in the README.

**Comment by modius** [comment]
We were not aware of MaterializeCSS at the time we started the project.  We are still not very familiar with the project or how it compares and contrasts with our own.

I'm not sure what prior art you are referring to. 

This project is an adaption of Google's Material project, based on Bootstrap.

**Comment by dandv** [comment]
When I'm comparing solutions, the ones that mention existing solutions and how they differentiate, win. That's because the authors show awareness of alternatives, and likely having learned from their mistakes, and also because as a user, I can better decide which tool is best for the job.

Since the README is under construction, I was just trying to figure out if the Daemonite team had looked at existing solutions before starting Material, and how they position the library vs. the others. For instance, MUI is minimalistic, Bootswatch Paper is a Bootstrap theme without custom JavaScript etc.

**Comment by modius** [comment]
That's not a bad idea at all.  I'll reopen and collect a list of alternate projects here for future comparison.

**Comment by dandv** [comment]
Awesome, thanks!

**Comment by devel-pa** [comment]
I can give you some hints comparing the two:

1.
Material is built like a seed where the architectural choices are driven by the HTML pages included in the project.
Materialize is built like a framework, install based on bower. (not tested with npm)
2.
Material is built upon many dependencies.
Materialize only dependency is jQuery. (which is a big fake as in fact a lot of libs are copied inside)
3.
Material CSS is built based Bootstrap 3, mainly by rewriting some of its components and removing others (same with the other dependencies)
Materialize CSS looks original, its structure still remembers about the popular CSS frameworks. I think it has really big influences.
4. (personal)
Material is awesome but really difficult to use. 
Materialize is pretty good and pretty easy to use.

Paul

**Comment by modius** [comment]
Thanks Paul! 

When you say Material is really difficult to use, is there anything that would make life easier?  Is it the lack of documentation or the underlying approach you find problematic?

**Comment by devel-pa** [comment]
Hi,

I want to say that my opinion is highly subjective and connected more with my projects (SPAs - with only one HTML page with almost no markup)

My issues:
- difficult to follow the dependencies (as of today some are hidden into HTMLs files and others in JS files). 
- rewritten CSS libraries add the need of loading the original libraries (for untreated components), too, that makes the CSS pretty big and tricky

**Comment by dandv** [comment]
BTW, in the meantime I've given a 3-minute talk on [prior art](http://slides.com/dandv/prior-art).

**Comment by modius** [comment]
The primary goal of this project is to give all Bootstrap components and elements a Material Design look, so it allows web developers to continue using the exact same Bootstrap HTML markup they are familiar with, but presents a final outcome that is in line with the principles and specifics of Google Material Design.

A secondary goal of this project is to add support of some unique Material Design components such as floating action buttons, pickers and steppers to name a few, which cannot be achieved by transforming existing Bootstrap components or elements.

The Bootstrap 4 release now approaches things differently.. namely:

> Replacing bootstrap.min.css on the site with material.min.css from this project without any other changes will transform all components and elements into a materialised look.

Hopefully that makes life simpler for all, and clearly articulates prior art as simply Bootstrap and Material.
