### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by leozdim** [Daemonite/material#55]
Cannot be loaded font awesome or ¿how should we must load it?

**Comment by sesemaya** [comment]
hi @leozdim 

by default, font awesome icons are stored at `/css/fonts/`
you may need to modify the `$css-path` in `/sass/_variable.scss` or `$fa-font-path` in `/sass/addon/font-awesome/_variable.scss` depending on how you set up your site.

**Comment by sesemaya** [comment]
Hi @leozdim 

Material no longer includes Font Awesome by default. You now need to load Font Awesome separately.
