### ISSUE TITLE
Bad pratice of javascript:void(0) in templates ?

### ISSUE THREAD

**Issue by Ugarz** [Daemonite/material#58]
Hi, was wondering something.
## Context
I was looking to play with you repo' and as I was reading a topic on good practices on javascript I noticed that in your page there is a lot of " javascript:void(0) " in href attributes.
## The fact
" There is no need to use knowing that the javascript code does not belong in an href attribute of a tag <a>. In the href attribute of a link must appear a valid URI that points actually on a resource, in this case javascript: is treated as a protocol! Protocol that does not exist; the link is then invalid and useless. At the time of web accessible, it's task. Replace the URI with an empty anchor, the famous <a href="#" onclick="action();"> </a> action is as bad.
To add an event to a link - for example on a confirmation link or delete the management with "AJAX" loading a link - so, use Event onclick. To confirm deletion, can be used, for example:
```
<a href="/delete/id" onclick="return confirm('Delete this object ?');">delete object</a>.
```
" -- end of citation.

[cf: OpenClassRoom](https://openclassrooms.com/courses/bonnes-pratiques-javascript#/id/r-1183986)

## Question
Why keep this behaviour ? Is there a meaning behind this I didn't find ?

**Comment by sesemaya** [comment]
hi @Ugarz this is simply to keep the browser stay on the same page when those links are clicked because they all are placeholders (for the purpose of showing how an element will look like). these links are not actually linking to anywhere. in a real project, these `href` values will probably be actual links/urls.

**Comment by Ugarz** [comment]
Thanks for the reply !
I see now why you let thoses elements ! :+1:  :smile:
