### ISSUE TITLE
DOC ui-tile.html: Tiles with Actions: text-overflow doesn't work for long texts on small screens

### ISSUE THREAD

**Issue by avirexavier** [Daemonite/material#59]
Hi,

It's a correction/adaptation of the documentation or your CSS file.
The ```text-overflow``` doesn't work for long texts on small screens in tiles with actions.

**File:** ui-tile.html
**Section:** Tiles with Actions

**Code:**
```
<div class="tile-inner">
	<span class="text-overflow">consectetur adipiscing elit, consectetur adipiscing elit, consectetur adipiscing elit</span>
</div>
```

**Screenshot:**
![tile_text_wo_overflow](https://cloud.githubusercontent.com/assets/13535100/9080857/ec87dea6-3b57-11e5-8e80-e0e20678561a.png)

**When the code works correctly:**
```
<div class="tile-inner text-overflow">
	<span class="">consectetur adipiscing elit, consectetur adipiscing elit, consectetur adipiscing elit</span>
</div>
```
![tile_text_w_overflow](https://cloud.githubusercontent.com/assets/13535100/9080856/ec86608a-3b57-11e5-958b-a76128c3f7bb.png)

Kind Regards

**Comment by sesemaya** [comment]
hi @avirexavier good find. this is actually because of firefox's implementation of the new flexbox spec (https://support.mozilla.org/en-US/questions/1030626)

anyway, `.tile-inner` has been updated and now even the original html will work just fine.
