### ISSUE TITLE
Many issues with the JavaScript files in Meteor

### ISSUE THREAD

**Issue by athmangude** [Daemonite/material#6]
I really like this project and I would have a little fun with it in Meteor and Cordova. I tried checking out the templates from a PHP server and everything works fine. However, when I put them in a Meteor they don't seem to look and behave as they should. Is there something I am not doing right? Is it Meteor or there are known issues with meter.

Here's my app structure:
```
├── application_layout_minimal.html
├── client
│   ├── css
│   │   └── base.min.css
│   ├── lib
│   │   └── material
│   │       ├── base.js
│   │       ├── html5shiv.js
│   │       └── respond.js
│   └── templates
│       ├── application
│       │   └── application_layout_minimal.html
│       ├── authentication
│       └── home
├── index.html
├── lib
│   ├── collections
│   └── router.js
├── page-404.html
├── page-affix-full.html
├── page-affix.html
├── public
│   ├── css
│   │   └── fonts
│   │       ├── FontAwesome.otf
│   │       ├── fontawesome-webfont.eot
│   │       ├── fontawesome-webfont.svg
│   │       ├── fontawesome-webfont.ttf
│   │       ├── fontawesome-webfont.woff
│   │       ├── fontawesome-webfont.woff2
│   │       ├── MaterialDesignIcon.eot
│   │       ├── MaterialDesignIcon.svg
│   │       ├── MaterialDesignIcon.ttf
│   │       └── MaterialDesignIcon.woff
│   └── images
│       ├── samples
│       │   ├── landscape.jpg
│       │   └── portrait.jpg
│       ├── screenshots
│       │   ├── material01.png
│       │   ├── material02.png
│       │   └── material03.png
│       └── users
│           └── avatar-001.jpg
└── server
```

**Comment by sesemaya** [comment]
@athmangude 

i doubt this is an issue with the material js because the templates work just fine: http://daemonite.github.io/material/

more like an issue either with meteor or with your particular setup. you may check the console and see what the problems are.

**Comment by modius** [comment]
h/t http://labs.daemon.com.au/t/material-html5-ui-design-based-on-google-material/19/7

> I managed to get it working. Referencing the files wasn't the issue since Meteor picks stylesheet and JavaScript files automatically. Even though I still get the error message on the console, I removed base.js and added the individual files in src folder to client/lib/material on my app and everything worked fine. **@athmangude**

**Comment by athmangude** [comment]
@modius That was me thinking I had fixed the issue but no. I only managed to get the side navs working but the material form elements, date picker, and many of the things that make this project awesome are still not working in Meteor
