### ISSUE TITLE
Webfonts - Icons - not working properly

### ISSUE THREAD

**Issue by Blackmoonx** [Daemonite/material#62]
Using Opera on Android, icons like hamburger menu, plus, etc.. are not showing (neither the code name). - on IE (windows phone) there is visible only code name "plus" or "menu".

**Comment by mtancoigne** [comment]
Is the font loaded correctly ?
Do you compile Material as part as your own design ?

I was going to open an issue to update the `sass/addons/material-design-icons/_path.scss` with proper font path (the one defined in `sass/addons/material-design-icons/_variables.scss` : there are two different pathes used to load the font...

**Comment by sesemaya** [comment]
Hi @Blackmoonx,

Material Design Icon uses a typographic feature called [igatures](http://alistapart.com/article/the-era-of-symbol-fonts), this allows rendering of an icon glyph simply by using its textual name, which is what has been done in the documentation site. However [some browsers](http://caniuse.com/#search=ligature) do not support this feature just yet. For browsers that do not support ligatures, fall back to specifying the icons using numeric character references like the example below:
```
<span class="icon">&#xE87C;</span>
```

Numeric character references can be found at `/css/fonts/codepoints`
