### ISSUE TITLE
error to install from bower

### ISSUE THREAD

**Issue by klausgao** [Daemonite/material#63]
I tried to install it by Bower with cmd: bower install --save git://github.com/Daemonite/material
at finished, I found its version is 1.0.0 (like).
and then tried to cmd bower install --save git://github.com/Daemonite/material#1.2.0, told not this version.

**Comment by drinkbird** [comment]
try
bower install https://github.com/Daemonite/material.git

**Comment by sesemaya** [comment]
registered as a bower package: daemonite-material in commit https://github.com/Daemonite/material/commit/405ed75f00c1f629e8fb0bd1cc4a2c132622d049
