### ISSUE TITLE
Styling for video tag

### ISSUE THREAD

**Issue by hamidabdulmalik** [Daemonite/material#67]
It will be good to get a better styling for a video tag, I cannot make a video tag fill a card. Hope you can fix that soon.

**Comment by sesemaya** [comment]
Hi @hamidabdulmalik,

This to me is more like project/user specific styles and I don't think we'll add this to the framework.

However it is very easy to make a html5 video tag fill a card, simply treat it like a block element:
```
video {
    height: 100%;
    width: 100%;
}
```
