### ISSUE TITLE
Material Checkboxes & Radio Buttons don't work with Chrome for iOS

### ISSUE THREAD

**Issue by atasc** [Daemonite/material#69]
Material Checkboxes & Radio Buttons don't work with Chrome for iOS,
you can test on your demo http://daemonite.github.io/material/ui-form-adv.html

**Comment by cubeel** [comment]
I remember the early version is ok with Chrome for iOS(version < 9), I don't know if related with ios 9

**Comment by atasc** [comment]
You are right, on iOS 7 it works, don't know if it works on iOS 8.
Is a fix for iOS 9 possible?

**Comment by atasc** [comment]
Any news?

**Comment by modius** [comment]
@sesemaya is away until next week. You are unlikely to see a response until then :(

**Comment by sesemaya** [comment]
Tested on `Chrome 47`, `iOS 9.2` and checkboxes and radio buttons work.

**Comment by AlastairTaft** [comment]
Seeing this issue on Chrome 47, iOS 8.3

**Comment by AlastairTaft** [comment]
Issue happens in the Samsung browser too (unfortunately do not have version issue) but likely the most up to date version at the time of writing this.
