### ISSUE TITLE
Missing Pagination

### ISSUE THREAD

**Issue by hervethouzard** [Daemonite/material#70]
Hello,

If one day you have some time, think to the pagination ;-)

Bye,
Hervé

**Comment by modius** [comment]
> It's a hard one. All of our implementations have used an infinity scroll -- ie no pagination, you just keep scrolling and dynamically loading more results to the list. I can't even find a reference to pagination theory in Google's Material spec

http://labs.daemon.com.au/t/pagination-in-the-material-html-5-ui/40

If you have a suggestion for how you would like to see pagination look please let us know in the forum.
