### ISSUE TITLE
Customizing datepicker

### ISSUE THREAD

**Issue by jkcybertron** [Daemonite/material#71]
Hello

Can you tell me how I can customize the years in datepicker.

In project.js, it is shown

<code>
$('.datepicker-adv-doc-2').datepicker({
	format: "dd/mmm/yyyy",
	selectMonths: true,
	selectYears: 20
});
</code>

but I want to show years not more than the current one, this shows 10 before and 10 after, meaning this will show year range from 2005 - 2025.
I want to show say from 1950 - current year. How can I do that?

Thanks
Jaskaran

**Comment by sesemaya** [comment]
hi @jkcybertron unfortunately the js doesn't support this yet. when the `selectYears` is specified with an even integer, the dropdown shows half before and half after the year in focus. for more details, please see this [page](http://amsul.ca/pickadate.js/date/#selectors)
