### ISSUE TITLE
Browser compatibility questions

### ISSUE THREAD

**Issue by babaggeii** [Daemonite/material#8]
What is the browser compatibility like? How would it fall back to <IE9?

**Comment by sesemaya** [comment]
hi @babaggeii material currently has not been tested extensively in ie 7 or 8 or 9, however the majority of the elements will work (but less the animation, etc.).

cards with secondary vertical area do not work in browsers that do not support `flexbox` right now.

anyway, this is still work in progress and we will continually add support for old ie and you are welcome to report any compatibility issues you may come across here.
