### ISSUE TITLE
Latest version with bower install

### ISSUE THREAD

**Issue by anthony-dibenedetto-olx** [Daemonite/material#80]
Installing with bower like this:

`bower install https://github.com/Daemonite/material.git --save`

The version returned is `1.3.0`.

This version, as far as I noticed, it's not the same version used in http://daemonite.github.io/material/, also not the same version in master branch.

I realized about this because of an error when tried to use the *_snackbar_* function documented in the site. I saw in *_base.js_* file a function called _toast_ that has basically the same signature of the *_snackbar_* in master brach.

Is there a way to install the latest version with bower?

**Comment by anthony-dibenedetto-olx** [comment]
Yes, there is:

- Deleted _material_ folder
- `bower cache clean`
- `bower install https://github.com/Daemonite/material.git#master --save`

That way now I have the lastest version. I should have tried that before.

**Comment by sesemaya** [comment]
registered as a bower package: daemonite-material in commit https://github.com/Daemonite/material/commit/405ed75f00c1f629e8fb0bd1cc4a2c132622d049

**Comment by anthony-dibenedetto-olx** [comment]
I just tried that but instead of resolving to [master](https://github.com/Daemonite/material/tree/master) branch it's resolving to [v1.3.0](https://github.com/Daemonite/material/tree/v1.3.0) tag.
