### ISSUE TITLE
Default text color back to blue.

### ISSUE THREAD

**Issue by hamidabdulmalik** [Daemonite/material#81]
Hi guys, you guys did a wonderful job with this, and I as far as I am concnerned, this is the best Material stuff out there. But please, can you change the default color back to blue, the way it used to? This pink color is not with it at all.

**Comment by Dark0rion** [comment]
You can customize the colors , using a custom CSS file and upload it to your site

**Comment by sesemaya** [comment]
Colours are managed via colour variables. You are free to change them on a project basis.
