### ISSUE TITLE
Documentation for CSS helpers / utilities classes

### ISSUE THREAD

**Issue by iniva** [Daemonite/material#84]
Are you guys planning documenting the helper / utility classes you have? 

Looking at the examples, I sometimes come across some of them, like `.margin-top` for example. They are very useful and I know there are many more I haven't seen. Those are the kind of added values that help us do things faster but it's a waste of your effort because they aren't documented.

**Comment by sesemaya** [comment]
apparently bootstrap 4 also introduces margin/padding helper classes: http://v4-alpha.getbootstrap.com/components/utilities/#spacing, so in the new `back-filling-bootstrap-4` branch we renamed our helper classes to stay in line with bootstrap 4's class names

**Comment by sesemaya** [comment]
The latest documentation site now has detailed information about utility classes

For example: http://daemonite.github.io/material/gh-pages/utilities/borders/index.html
