### ISSUE TITLE
Bootstrap like Navbar

### ISSUE THREAD

**Issue by ngaurav** [Daemonite/material#86]
Material design has got most of the things write. But is there any Navbar-fixed-top like class in this framework, which automatically collapses on devices with low width?

**Comment by ngaurav** [comment]
@sesemaya can you please suggest me possible restructuring for my [site](52.28.11.1)

**Comment by ngaurav** [comment]
In [http://daemonite.github.io/material/ui-tab.html](http://daemonite.github.io/material/ui-tab.html) when we scroll down the tabs in the centre disappear they should stick as a second bar on the top. This happens in [https://gaming.youtube.com/game/UCT1tnevF8bn9Nwr6ZHA9Mag](https://gaming.youtube.com/game/UCT1tnevF8bn9Nwr6ZHA9Mag)

@sesemaya I think this feature will should be brought to material.

**Comment by sesemaya** [comment]
All Bootstrap CSS selectors and HTML markup (including `.navbar-fixed-top`) are now supported since https://github.com/Daemonite/material/releases/tag/v4.0.0-alpha.0
