### ISSUE TITLE
Modal in Nav

### ISSUE THREAD

**Issue by HighTechnological** [Daemonite/material#88]
If the `<ul clаss = "nаv">` register `data-toggle = "modal"` and add a reference to the modal window, the window appears on top of the curtain, and she was not removed (as opposed to a straight html link), how to do that would be it was removed automatically?

**Comment by sesemaya** [comment]
You probably should not add `data-toggle="modal"` to a `<ul class="nav">`. It probably should not be `.nav` then, or you should move `data-toggle` to individual `<a>`s.
