### ISSUE TITLE
Call the toast programmatically

### ISSUE THREAD

**Issue by andyjessop** [Daemonite/material#9]
I can only find info for toggling it with a button.

**Comment by modius** [comment]
> @sesemaya  current toast is mainly to provide the styles, and the javascript side of it certainly needs improvement in future releases. for example, replace triggering with bootstrap's tooltip javascript with something more like this: https://github.com/CodeSeven/toastr 

This is discussed on the forum:
http://labs.daemon.com.au/t/question-about-toasts/53

**Comment by modius** [comment]
Sorry, reopening rather than creating a new issue.  We intend to add Toasting programatically when we get a chance.

**Comment by sesemaya** [comment]
this functionality has been added since https://github.com/Daemonite/material/commit/6fec4a615a32ad8456ae61d37ec014adce7d420e

for how-to, feel free to check the latest `templates/ui-modal.html` and `js/project.js` (or `js/project.min.js`)
