### ISSUE TITLE
Header Background Image

### ISSUE THREAD

**Issue by cansanet** [Daemonite/material#91]
Hi, thank you for this awesome compilation.
I would like to ask you, how to change the dynamically generated header background image.
When I run grunt, header background image is created automatically. 
But how can I change the style of that image.
Thank you.

**Comment by sesemaya** [comment]
You can change that in `assets/sass-project/project.scss`

**Comment by cansanet** [comment]
I dont mean changing the path of this element in scss file, I want to change automatically generated image files itself (images/bg/brand.jpg, images/brand-accent.jpg etc). When you run grunt something generates these awesome colorful files, but which file is generating these images.

**Comment by sesemaya** [comment]
These images are not generated. They are just static images.
