### ISSUE TITLE
why not add a quick compile script to Gruntfile.js?

### ISSUE THREAD

**Issue by klausgao** [Daemonite/material#93]
just add:

```
grunt.registerTask('default', ['sass:all', 'postcss:all', 'concat:all', 'uglify:all', 'cssmin:all']);
```

**Comment by sesemaya** [comment]
the grunt file has been updated in the `back-filling-bootstrap-4` branch and it adds a few default scripts to compile css and js for material, project or both.

**Comment by sesemaya** [comment]
The following tasks have been added:
* `default` - generate full and minified CSS and JavaScript for material and project
* `material` - generate full and minified CSS and JavaScript for material
* `material-css` - generate full and minified CSS for material
* `material-js` - generate full and minified JavaScript for material
* `project` - generate full and minified CSS and JavaScript for project
* `project-css` - generate full and minified CSS for project
* `project-js` - generate full and minified JavaScript for project
