### ISSUE TITLE
Adding Default to variables and colours sass

### ISSUE THREAD

**Issue by treforcoster** [Daemonite/material#99]
I'm using the npm version of this so not sure how up to date it is but could I suggest adding  "!default" to the declaration of colours and vars in the  "_colours.scss" and "_variables.scss". This would allow users to override these vars in our project files rather than tamper with the main material files.

Thanks

**Comment by sesemaya** [comment]
this has been fixed in the `back-filling-bootstrap-4` branch, although this new branch is still work in progress, we are looking to have an alpha version ready in the near future

**Comment by sesemaya** [comment]
Closing as `backfilling-bootstrap-4` has been merged into `master`.
